<?php

return [
    'key' => 'sseo.redirects',
    'provider' => \Seiger\sSeo\Tables\RedirectsTableData::class,
    'wire_target' => 'search,perPage,setSort,switchView,openCreateModal,openEditModal,saveModal,closeModal,openDeleteModal,closeDeleteModal,deleteConfirmed,goToPage,firstPage,previousPage,nextPage,goLastPage',
    'per_page' => 20,
    'per_page_options' => [10, 20, 50, 100],
    'views' => ['table', 'list'],
    'default_view' => 'table',
    'default_sort' => 'old_url',
    'default_direction' => 'asc',
    'search' => [
        'enabled' => true,
        'state' => 'search',
    ],
    'actions' => [
        [
            'key' => 'create',
            'type' => 'wire',
            'method' => 'openCreateModal',
            'icon' => 'plus',
            'label' => 'sSeo::global.add_redirect',
            'tone' => 'success',
            'icon_only' => true,
        ],
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
            'icon_only' => true,
            'selection' => 'single',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
            'icon_only' => true,
            'selection' => 'single',
        ],
    ],
    'filters' => [],
    'columns' => [
        ['key' => 'id', 'type' => 'text', 'label' => 'ID', 'class' => 'evo-ui-table__number-column evo-ui-table__id-column', 'sortable' => true, 'sort_field' => 's_redirects.id'],
        ['key' => 'old_url', 'type' => 'text', 'label' => 'sSeo::global.old_url', 'class' => 'evo-ui-table__title-column', 'sortable' => true, 'sort_field' => 's_redirects.old_url'],
        ['key' => 'new_url', 'type' => 'text', 'label' => 'sSeo::global.new_url', 'sortable' => true, 'sort_field' => 's_redirects.new_url'],
        ['key' => 'type', 'type' => 'badge', 'label' => 'sSeo::global.redirect_type', 'sortable' => true, 'sort_field' => 's_redirects.type'],
        ['key' => 'site_key', 'type' => 'badge', 'label' => 'sSeo::global.site_key', 'sortable' => true, 'sort_field' => 's_redirects.site_key'],
        ['key' => 'updated_at', 'type' => 'date', 'label' => 'global.date', 'class' => 'evo-ui-table__date-column', 'sortable' => true, 'sort_field' => 's_redirects.updated_at'],
    ],
    'list' => [
        'media' => false,
        'compact' => false,
        'title' => 'old_url',
        'subtitle' => 'new_url',
        'meta' => ['type', 'site_key', 'updated_at'],
    ],
    'modal' => [
        'enabled' => true,
        'row_dblclick' => true,
        'icon' => 'refresh-cw',
        'size' => 'lg',
        'title_create' => 'sSeo::global.add_redirect',
        'title_edit' => 'sSeo::global.redirects',
        'submit_label' => 'evo::global.action_save',
        'cancel_label' => 'evo::global.action_cancel',
        'notices_position' => 'after_fields',
        'notices' => [
            [
                'tone' => 'info',
                'icon' => 'alert-triangle',
                'title' => 'sSeo::global.warning',
                'body' => 'sSeo::global.message_for_large_number_redirects',
            ],
        ],
        'fields' => [
            [
                'name' => 'old_url',
                'type' => 'text',
                'label' => 'sSeo::global.old_url',
                'help' => 'sSeo::global.old_url_help',
                'hint' => 'sSeo::global.old_url_hint',
                'placeholder' => 'sSeo::global.old_url_placeholder',
                'span' => 'full',
                'rules' => ['required', 'string', 'max:255'],
            ],
            [
                'name' => 'new_url',
                'type' => 'text',
                'label' => 'sSeo::global.new_url',
                'help' => 'sSeo::global.new_url_help',
                'hint' => 'sSeo::global.new_url_hint',
                'placeholder' => 'sSeo::global.new_url_placeholder',
                'span' => 'full',
                'rules' => ['required', 'string', 'max:255'],
            ],
            [
                'name' => 'type',
                'type' => 'select',
                'label' => 'sSeo::global.redirect_type',
                'help' => 'sSeo::global.redirect_type_help',
                'hint' => 'sSeo::global.redirect_type_hint',
                'options' => [
                    ['value' => '301', 'label' => '301'],
                    ['value' => '302', 'label' => '302'],
                    ['value' => '307', 'label' => '307'],
                ],
                'rules' => ['required', 'integer', 'in:301,302,307'],
            ],
            [
                'name' => 'site_key',
                'type' => 'select',
                'label' => 'sSeo::global.site_key',
                'help' => 'sSeo::global.site_key_help',
                'hint' => 'sSeo::global.site_key_hint',
                'options_provider' => 'modalOptionsForField',
                'rules' => ['nullable', 'string', 'max:120'],
            ],
        ],
    ],
    'row_actions' => [
        [
            'key' => 'edit',
            'type' => 'wire',
            'method' => 'openEditModal',
            'argument' => 'id',
            'icon' => 'edit',
            'label' => 'global.edit',
            'tone' => 'primary',
        ],
        [
            'key' => 'delete',
            'type' => 'wire',
            'method' => 'openDeleteModal',
            'argument' => 'id',
            'icon' => 'trash',
            'label' => 'global.remove',
            'tone' => 'danger',
        ],
    ],
];
