// @ts-ignore
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docs: [{ type: 'autogenerated', dirName: '.' }], // ← крапка, не 'pages'
};

export default sidebars;
